version: '3'
services:
  flask:
    build: .
    volumes:
      - ./results:/app/results
    expose:
      - "5000"
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./results:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
