---
- hosts: targets
  gather_facts: yes
  vars:
    output_dir: "{{ lookup('env', 'OUTPUT_DIR') | default('results', true) }}"
  tasks:
    - name: Ensure output directory exists on controller
      file:
        path: "{{ output_dir }}"
        state: directory
      delegate_to: localhost

    - name: Get user list
      command: getent passwd
      register: user_list

    - name: Get listening ports
      command: ss -tulwn
      register: port_list

    - name: Get disk usage
      shell: df -h --output=size,used,avail,pcent / | tail -n 1
      register: disk_usage

    - name: Get memory info
      shell: free -m | grep 'Mem:'
      register: memory_info

    - name: Get CPU load
      command: cat /proc/loadavg
      register: cpu_load

    - name: Get network stats
      command: cat /proc/net/dev
      register: net_stats

    - name: Get temperature sensors
      command: sensors
      register: sensor_data
      ignore_errors: yes

    - name: Save facts to JSON
      copy:
        dest: "{{ output_dir }}/facts_{{ inventory_hostname }}.json"
        content: |
          {
            "hostname": "{{ ansible_facts.hostname }}",
            "users": {{ user_list.stdout_lines | to_json }},
            "ports": {{ port_list.stdout_lines | to_json }},
            "disk": {{ disk_usage.stdout | to_json }},
            "memory": {{ memory_info.stdout | to_json }},
            "cpu_load": {{ cpu_load.stdout | to_json }},
            "net": {{ net_stats.stdout_lines | to_json }},
            "sensors": {{ sensor_data.stdout_lines | to_json }}
          }
      delegate_to: localhost
