name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run black check
        run: black --check .
      - name: Run flake8
        run: flake8
      - name: Run tests
        run: pytest
      - name: Build Docker image
        run: docker build -t autocfg:ci .
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.12.0
        with:
          image-ref: autocfg:ci
          format: table
          ignore-unfixed: true
          exit-code: 1
          severity: CRITICAL,HIGH
